import { NextResponse } from "next/server";

/*
 * Create new User
 *
 * Params:
 *  None
 * Request body:
 *  first: first name
 *  last: last name,
 *  email_address: email address
 *  pfp: path to pfp image [optional]
 * Return:
 *  data: id of the new User generated by firestore
 *  error: error or null
*/
export async function POST(req: Request) {
  // get new user data from req body
  const data = await req.json();
  const { first, last, email_address, pfp } = data;

  // TODO: validate input

  const user: User = {
    "first": first,
    "last": last,
    "email_address": email_address,
    "active_listings": [],
    "interested_listings": [],
    "completed_sales": 0,
    "completed_purchases": 0,
    "cum_buyer_rating": 0,
    "cum_seller_rating": 0,
    "pfp": pfp,
    "id": '',
  };

  // TODO: call firestore api to add User object (should also set the id field and return the full user object)

  return NextResponse.json({ data: { user_id: user.id }, error: null });
}
